version: '3.9'
services:
  local-db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - local-db:/var/lib/postgresql/data
volumes:
  local-db:
    driver: local
