version: '3.9'
services:
  local-api:
    container_name: local-api
    build:
      context: .
      target: development
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev && npm run start:dev"
    volumes:
      - ./src:/src
      - /usr/node_modules
    depends_on:
      - local-db
  local-db-studio:
    container_name: local-db-studio
    build:
      context: .
      target: development
    restart: always
    ports:
      - 5555:5555
    env_file:
      - .env
    command: >
      sh -c "npm run prisma:studio"
    volumes:
      - ./src:/src
      - /usr/node_modules
    depends_on:
      - local-db
  local-db:
    image: postgres:13
    container_name: local-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - local-db:/var/lib/postgresql/data
volumes:
  local-db:
    driver: local
