org: crislemus
app: job-quest-api
service: job-quest-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

custom:
  appSecrets: ${ssm:/aws/reference/secretsmanager/JobQuestApi}

functions:
  main:
    handler: dist/main.handler
    environment:
      DATABASE_URL: ${self:custom.appSecrets.DATABASE_URL}
      JWT_SECRET: ${self:custom.appSecrets.JWT_SECRET}
      JWT_REFRESH_SECRET: ${self:custom.appSecrets.JWT_REFRESH_SECRET}
      ADMIN_REGISTER_KEY: ${self:custom.appSecrets.ADMIN_REGISTER_KEY}
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
